app/Http/routes.php
<?php


// This needs to be here to stop the error
// count(): Parameter must be an array or an object that implements Countable
if(version_compare(PHP_VERSION, '7.2.0', '>=')) {
    error_reporting(E_ALL ^ E_NOTICE ^ E_WARNING);
}


// This lets me see errors when debugging
// ini_set('display_errors', 1);
//     ini_set('display_startup_errors', 1);
//     error_reporting(E_ALL);


// \Event::listen('Illuminate\Database\Events\QueryExecuted', function ($query) {
//     echo '<pre>';
//     var_dump($query->sql);
//     echo '</pre>';
//     var_dump($query->bindings);
//     // var_dump($query->time);
// });

/*
|--------------------------------------------------------------------------
| Application Routes
|--------------------------------------------------------------------------
|
| Here is where you can register all of the routes for an application.
| It's a breeze. Simply tell Laravel the URIs it should respond to
| and give it the controller to call when that URI is requested.
|
 */

 Route::get('session', function(){
    dd($_COOKIE);
    dd(session()->all());

 });

 Route::get('media/{typeid}', function($typeid){

return '<div  class="modal">
<p>Thanks for clicking. That felt good.</p>
<a href="#" rel="modal:close">Close</a>
</div>';

 });

// Mini CMS includes pages controller
// and pages admin controller
Route::get('/page/{slug}','PagesController@index')->name('page');

// Manager for CMS - pages and resources management
Route::group(['middleware'=>'auth'], function() {

    Route::get('/content/manager','ContentManagementController@index')->name('content.manager');

});




 // RegenClientPrices
 Route::get('regenclientprices','ProductController@regenClientPrices');

 // Route to export list of all items needing to be picked for pickOrders
Route::get('export/items/picklist',['uses'=>'ExportPickOrderItemsController@export', 'as'=>'picklist']);


 Route::get('updatedb/','DBUpdateController@index');

Route::get('testy/', 'ClientPricingController@add_product');

Route::get('test/{typeid}', 'ProductTypeImageController@doSortIfRequired');

// Route::get('reports', 'ProductReportsController@index');

// sorts a productTypeImage list

// Route::get('/', function () {

//     //return \Auth::guard('web')->user();
//     return view('welcome');
// });

Route::auth();
Route::get('ecatgw', 'Auth\EcatalogGatewayController@index'); // links from eCat
Route::get('/', ['as' => 'welcome', 'uses' => 'HomeController@welcome']);
Route::get('/home', ['as' => 'home', 'uses' => 'HomeController@index']);

// FILTER LISTS
Route::post('filter/{name}', 'FilterController@index');

// PRODUCT ROUTES
Route::resource('product', 'ProductController');
Route::get('product/{id}/orders',['as'=>'productorders', 'uses'=>'ProductController@orders'] );
Route::post('product/setsalesperiod','ProductController@setSalesPeriod');
Route::post('products/bulkupdate','ProductController@bulkUpdate');

Route::get('shopify/export',[
    'as' => 'shopify.export',
    'uses' =>'ShopifyExportController@initialExport'
]);

Route::get('shopify', 'ShopifyImportController@index');

Route::post('shopify/import','ShopifyImportController@import');

// BOM ROUTES
Route::resource('bom', 'BomController');

// PRODUCT TYPE , TYPE_OPTION , TYPE IMAGES

Route::resource('type', 'ProductTypeController');

// Routes for importing products via xls
Route::get('import/products',['uses' =>'ImportProductsController@index']);
Route::post('import/products',['uses' => 'ImportProductsController@import']);
// Route for exporting full product list
Route::get('export/products',['uses'=>'ExportProductsController@export']);

// Clients Export and import utils
Route::get('import/clients',['uses' =>'ImportClientsController@index']);
Route::post('import/clients',['uses' => 'ImportClientsController@import']);
Route::get('export/clients',['uses'=>'ExportClientsController@export']);

Route::resource('typeoption', 'ProductTypeOptionController');
Route::get('typeoption/{typeid}/{opt}', [
    'as' => 'typeoption.edit', 'uses' => 'ProductTypeOptionController@edit']);
Route::post('typeoption/{typeid}/{opt}', [
    'as' => 'typeoption.update', 'uses' => 'ProductTypeOptionController@update']);
// PRODUCT TYPE IMAGE ROUTES
Route::resource('producttypeimage', 'ProductTypeImageController');



// ajax handlers for sort, upload and deleting of product images
Route::post('ajax/image/sort', 'ProductTypeImageController@sort');
Route::post('ajax/image/upload/{typeid}', 'ProductTypeImageController@upload');
Route::post('ajax/image/delete/{imageid}', 'ProductTypeImageController@delete');

// Product Type Files
Route::get('producttypefile','ProductTypeFileController@index')->name('producttypefile.index');

// ajax handlers for sort, upload and deleting of product type files
Route::post('ajax/file/sort', 'ProductTypeFileController@sort');
Route::post('ajax/file/upload/{typeid}', 'ProductTypeFileController@upload')->name('producttype.file.upload');
Route::post('ajax/file/delete/{id}', 'ProductTypeFileController@delete');

// CATEGORY ROUTES
Route::resource('category', 'CategoryController');
Route::get('category/{id}/delete', [
    'as' => 'category.delete', 'uses' => 'CategoryController@delete']);

// TYPE_CATEGORY ROUTES
Route::resource('typecategory', 'TypeCategoryController');

//ORDER ROUTES
Route::resource('order', 'OrderController');
Route::get('order/{id}/pick', [
    'as' => 'order.pick', 'uses' => 'OrderController@pick']);

// ORDER EXPORT ROUTES
Route::get('export/{id}/export', [
    'as' => 'export.myob', 'uses' => 'ExportController@export']);
Route::post('export/batchexport', [
    'as' => 'export.batchexport', 'uses' => 'ExportController@batchexport']);
Route::get('export/{id}/detail', [
    'as' => 'export.detail', 'uses' => 'ExportController@detail']);
Route::get('export/download', [
    'as' => 'export.download', 'uses' => 'ExportController@download']);

//ORDER ITEM ROUTES
Route::get('orderitem/{orderId}/{productCode}/edit', [
    'as' => 'order.edititem', 'uses' => 'OrderController@editOrderItem']);
Route::get('order/{orderId}/delete', [
    'as' => 'order.delete', 'uses' => 'OrderController@destroy']);
// PICKING ORDERS
Route::get('ajax/pickorder/{id}', 'OrderController@pickorderGet');
Route::post('ajax/pickorder/{id}', 'OrderController@pickorderStore');

//CLIENT ROUTES
Route::resource('client', 'ClientController');

// CLIENT PRICING ROUTES
Route::get('client/{id}/pricing', ['as' => 'client.pricing', 'uses' => 'ClientPricingController@index']);
//Route::post('client/{id}/pricing', ['as' => 'client.pricing', 'uses' => 'ClientController@storePricing']);
Route::post('ajax/client/price', ['as' => 'client.price.ajax', 'uses' => 'ClientPricingController@ajax']);

// STAFF ROUTES
Route::resource('staff', 'StaffController');

//PROSPECTOR
Route::get('prospector', [
    'as' => 'prospector.index', 'uses' => 'Prospector\HomeController@index']);
Route::get('prospector/accounts', [
    'as' => 'prospector.accounts.index', 'uses' => 'Prospector\AccountsController@index']);

// Freight Calculator
// Route::get('freight/location', [
//     'as' => 'freight.location', 'uses' => 'FreightCalculatorController@searchForLocation']); // ajax data for location autocomplete
// Route::get('freight', [
//     'as' => 'freight.index', 'uses' => 'FreightCalculatorController@index']);
// Route::post('freight/quote', [
//     'as' => 'freight.quote', 'uses' => 'FreightCalculatorController@quote']);

// Client search for ajax autocomplete selectors
Route::get('clientlookup/', [
    'as' => 'clientlookup', 'uses' => 'ClientLookupController@index']); // ajax data for client lookup autocomplete

// Load freight data from spreadsheets
Route::get('freight/{postcode?}', 'FreightController@index');

// Stock Adjuster
Route::get('stockadjust', 'StockAdjustController@index');
Route::post('stockadjust/find', 'StockAdjustController@find');
Route::post('stockadjust/{product}', 'StockAdjustController@update');

// Analtyics
Route::get('analytics',['as'=>'analytics.index','uses'=>'Analytics\HomeController@index']);
Route::get('analytics/customers',['as'=>'analytics.customers','uses'=>'Analytics\CustomersController@index']);
Route::get('analytics/orders',['as'=>'analytics.orders','uses'=>'Analytics\OrdersController@index']);

// Call Planner
Route::get('analytics/calls',['as'=>'analytics.calls','uses'=>'Analytics\CallController@index']);
Route::get('analytics/call/{rep}',['as'=>'analytics.call','uses'=>'Analytics\CallController@plan']);

require __DIR__.'/routes_catalog.php';

resources/views/admin/type/create.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
    <div class="row">
        <div class="col-md-10 col-md-offset-1">
            <div class="panel panel-default">
                <div class="panel-heading">Product Types</div>

                <div class="panel-body">
                    <h3>Create Product Type</h3>

                    {!! Form::model($type, array('route' => array('type.store', $type->typeid ), 'method' => 'post' )) !!}

                    @include('admin.type.partials.form')

                     <button type="submit"  value="Create" class="btn btn-primary" >Create</button>


                    {!! Form::close() !!}
                </div>
            </div>
        </div>
    </div>
</div>
@endsection

resources/views/admin/type/create_option.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
    <div class="row">
        <div class="col-md-10 col-md-offset-1">
            <div class="panel panel-default">
                <div class="panel-heading">Product Types</div>

                <div class="panel-body">

					<h3>Create a Product Option</h3>

					{!! Form::open( array('route' => array('typeoption.store'), 'method' => 'post' )) !!}
					<input type="hidden" name="typeid" value="{{ $type->typeid }}" />

					<div class="form-group{{ $errors->has('opt_code') ? ' has-error' : '' }}">
					    {!! Form::label('opt_code', 'Opt code', array('class' => 'col-md-4 control-label')) !!}
					    <div class="col-md-6">
					    {!! Form::text('opt_code', null,  array('class' => 'form-control')) !!}

					    @if ($errors->has('opt_code'))
					        <span class="help-block">
					            <strong>{{ $errors->first('opt_code') }}</strong>
					        </span>
					    @endif
					    </div>
					</div>

					<div class="form-group{{ $errors->has('opt_desc') ? ' has-error' : '' }}">
					    {!! Form::label('opt_desc', 'Opt desc', array('class' => 'col-md-4 control-label')) !!}
					    <div class="col-md-6">
					    {!! Form::text('opt_desc', null,  array('class' => 'form-control')) !!}

					    @if ($errors->has('opt_desc'))
					        <span class="help-block">
					            <strong>{{ $errors->first('opt_desc') }}</strong>
					        </span>
					    @endif
					    </div>
					</div>

					<div class="form-group{{ $errors->has('opt_class') ? ' has-error' : '' }}">
					    {!! Form::label('opt_class', 'Opt class', array('class' => 'col-md-4 control-label')) !!}
					    <div class="col-md-6">
					    {!! Form::text('opt_class', null,  array('class' => 'form-control')) !!}

					    @if ($errors->has('opt_class'))
					        <span class="help-block">
					            <strong>{{ $errors->first('opt_class') }}</strong>
					        </span>
					    @endif
					    </div>
					</div>

					 <button type="submit"  value="Create" class="btn btn-primary" >Create</button>

					{!! Form::close() !!}

		@include('admin.type.partials.type_options', ['hide_add_link' => true, 'hide_edit_link' => true ])


                </div>
            </div>
        </div>
    </div>
</div>
@endsection

resources/views/admin/type/edit.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
    <div class="row">
        <div class="col-md-10 col-md-offset-1">
            <div class="panel panel-default">
                <div class="panel-heading">Product Types</div>

                <div class="panel-body">
                    <h3>Edit Product Type ({{ $type->typeid  }})</h3>

                    {!! Form::model($type, array('route' => array('type.update', $type->typeid ), 'method' => 'patch' )) !!}

                     @include('admin.type.partials.form')
                     <div class="form-horizontal">
                         <div class="form-group">
                             {!! Form::label('_delete', 'Delete type', array('class' => 'col-md-4 control-label')) !!}
                             <div class="col-md-6">
                             {!! Form::checkbox('_delete', $type->typeid  ) !!}

                             </div>
                         </div>

                         <div class="col-md-12">
                         <button type="submit"  value="Save" class="btn btn-primary" >Save</button>
                         </div>

                     </div>

                     {!! Form::close() !!}

                     @include('admin.type.partials.type_options',['hide_add_link'=>false,'hide_edit_link'=>false])

                     @include('admin.type.partials.type_products')

                     @include('admin.type.partials.type_images')

                     @include('admin.type.partials.type_files')


                     @include('admin.type.partials.type_categories')


                </div>
            </div>
        </div>
    </div>
</div>
@endsection

resources/views/admin/type/edit_option.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
    <div class="row">
        <div class="col-md-10 col-md-offset-1">
            <div class="panel panel-default">
                <div class="panel-heading">Product Types</div>

                <div class="panel-body">

					<h3>Edit Product Option</h3>

					<form method="post" action="{{ 
						route('typeoption.update',['typeid'=>$typeOption->typeid,'opt'=>$typeOption->opt_code ])}}" >
					<input type="hidden" name="_token" value="{{ csrf_token() }}" />


					<div class="form-group{{ $errors->has('opt_code') ? ' has-error' : '' }}">
					    {!! Form::label('opt_code', 'Opt code', array('class' => 'col-md-4 control-label')) !!}
					    <div class="col-md-6">
					    {!! Form::text('opt_code', $typeOption->opt_code,  array('class' => 'form-control')) !!}

					    @if ($errors->has('opt_code'))
					        <span class="help-block">
					            <strong>{{ $errors->first('opt_code') }}</strong>
					        </span>
					    @endif
					    </div>
					</div>

					<div class="form-group{{ $errors->has('opt_desc') ? ' has-error' : '' }}">
					    {!! Form::label('opt_desc', 'Opt desc', array('class' => 'col-md-4 control-label')) !!}
					    <div class="col-md-6">
					    {!! Form::text('opt_desc', $typeOption->opt_desc,  array('class' => 'form-control')) !!}

					    @if ($errors->has('opt_desc'))
					        <span class="help-block">
					            <strong>{{ $errors->first('opt_desc') }}</strong>
					        </span>
					    @endif
					    </div>
					</div>

					<div class="form-group{{ $errors->has('opt_class') ? ' has-error' : '' }}">
					    {!! Form::label('opt_class', 'Opt class', array('class' => 'col-md-4 control-label')) !!}
					    <div class="col-md-6">
					    {!! Form::text('opt_class', $typeOption->opt_class,  array('class' => 'form-control')) !!}

					    @if ($errors->has('opt_class'))
					        <span class="help-block">
					            <strong>{{ $errors->first('opt_class') }}</strong>
					        </span>
					    @endif
					    </div>
					</div>


					<div class="form-group">
					    {!! Form::label('_delete', 'Delete option', array('class' => 'col-md-4 control-label')) !!}
					    <div class="col-md-6">
					    {!! Form::checkbox('_delete', $typeOption->typeid ) !!}

					    </div>
					</div>

					 <button type="submit"  value="Update" class="btn btn-primary" >Update</button>

					{!! Form::close() !!}




                </div>
            </div>
        </div>
    </div>
</div>
@endsection

resources/views/admin/type/file.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
    <div class="row">
        <div class="col-md-10 col-md-offset-1">
            <div class="panel panel-default">
                <div class="panel-heading"><h3>Product Files</h3>

                </div>

                <div class="panel-body">
                     <div class="row" style="padding-top:10px;">
                        <div class="col-xs-2">
                          
                        </div>
                        <div class="col-xs-10">
                        <form id="file-form" action="#" method="post" enctype="multipart/form-data">
                            {{ csrf_field() }}
                            Upload a File (PDF):
                            <input type="file" id="uploadfile" name="uploadfile"><br />
                            <div style="margin: 10px 0 20px 0;padding:5px">Title: This is name that is displayed in the ecat download link.<link rel="stylesheet" href="" class=""><br /><input type="text" name="title" id="title" /></div>
                            <div style="margin: 10px 0 20px 0;padding:5px">Description: This is not currently used or displayed anywhere <br />
                            <input type="text" name="description" id="description" /></div>
                            <input type="submit" id="submit" name="submit" value="Upload File Now" >
                        </form>

                        <p id="status"></p>
                      
                        </div>
                    </div>

                      <div class="row" style="padding-top:10px;">
                        <div class="col-xs-10">
                          <div id="msgBox">
                          </div>
                        </div>
                      </div>

                      @if ($files && $files->count())
                        <ul id="filesortable" class="sortable list-group">
                         @foreach ($files as $i)
                         <li id="item-{{ $i->id }}" class="list-group-item">
                            <span>{{ $i->filename }}</span>
                            <span>{{ $i->title }}</span>
                            <span>{{ $i->description }}</span>
                         <a title="delete file" class="pull-right" ><i style="margin-top:-5px" class="fa fa-trash fa-2x" aria-hidden="true"></i></a> </li>

                         @endforeach
                         </ul>

                     @endif





                </div>
            </div>
        </div>
    </div>
</div>

@endsection

@section('script')
<script> 
var typeid = {{ $typeid }};
var uploadUrl = '{{ route("producttype.file.upload",["typeid"=>$typeid ]) }}';

// Sortable for type images
$( "#filesortable" ).sortable({

axis: 'y',
update: function (event, ui) {
    // do something?

    
}

});

// setup delete click handler to delete images
$('#filesortable li a').on('click', function(e){
var fileId = $(e.target).closest('li').attr('id').substring(5,20) 


$.post('ajax/file/delete/' + fileId, function(data) {
    if (data > 0){
        //$('#item-'+ data).remove(); // remove the deleted item
        location.reload();
    }
    
});


})






$( "#sortable" ).disableSelection();

</script>

<script>
(function(){
    var form = document.getElementById('file-form');
    var fileSelect = document.getElementById('uploadfile');
    var fileTitle = document.getElementById('title');
    var fileDescription = document.getElementById('description');
    var uploadButton = document.getElementById('submit');
    var statusDiv = document.getElementById('status');

    form.onsubmit = function(event) {
        event.preventDefault();

        statusDiv.innerHTML = 'Uploading . . . ';

        // Get the files from the input
        var files = fileSelect.files;

        // Create a FormData object.
        var formData = new FormData();

        //Grab only one file since this script disallows multiple file uploads.
        var file = files[0]; 

        //Check the file type.
        // input.files[0].type==='application/pdf'
        if (!file.type ==='application/pdf') {
            statusDiv.innerHTML = 'You cannot upload this file because it’s not a PDF.';
            return;
        }

        if (file.size >= 6000000 ) {
            statusDiv.innerHTML = 'You cannot upload this file because its size exceeds the maximum limit of  6 MB.';
            return;
        }

         // Add the file to the AJAX request.
        formData.append('uploadfile', file, file.name);
        // Add the file title value
        formData.append('title', fileTitle.value);
        // Add the file title value
        formData.append('description', fileDescription.value);

        // Set up the request.
        var xhr = new XMLHttpRequest();

        // Open the connection.
        xhr.open('POST', uploadUrl + '?_token='+ K9homes.csrfToken, true);
    

        // Set up a handler for when the task for the request is complete.
        xhr.onload = function (data) {
            console.log(xhr.response);
            var resObj = JSON.parse(xhr.response);
            console.log(resObj);
           
          if (xhr.status === 200) {
            statusDiv.innerHTML = 'Your upload is successful..';
          } else {
            statusDiv.innerHTML = 'An error occurred during the upload. Try again.';
          }
          if(!resObj.error){
            location.reload(true);
          }
          statusDiv.innerHTML = 'An error occurred during the upload: ' + resObj.error ;
            
        
        };

        // Send the data.
        xhr.send(formData);
    }
})();

</script>
@endsection

resources/views/admin/type/image.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
    <div class="row">
        <div class="col-md-10 col-md-offset-1">
            <div class="panel panel-default">
                <div class="panel-heading"><h3>Product Images</h3>

                </div>

                <div class="panel-body">
                     <div class="row" style="padding-top:10px;">
                        <div class="col-xs-2">
                          <button id="uploadBtn" class="btn btn-large btn-primary">Choose File</button>
                        </div>
                        <div class="col-xs-10">
                      <div id="progressOuter" class="progress progress-striped active" style="display:none;">
                        <div id="progressBar" class="progress-bar progress-bar-success"  role="progressbar" aria-valuenow="45" aria-valuemin="0" aria-valuemax="100" style="width: 0%">
                        </div>
                      </div>
                        </div>
                    </div>

                      <div class="row" style="padding-top:10px;">
                        <div class="col-xs-10">
                          <div id="msgBox">
                          </div>
                        </div>
                      </div>

                      @if ($images->count())
                        <ul id="sortable" class="sortable">
                         @foreach ($images as $i)
                         <li id="item-{{ $i->id }}"><img src="{{ url('/source/tn/'.$i->filename.'?'.$i->updated_at->timestamp) }}" /> <a title="delete image" class="pull-right" style="padding: 10px"><i class="fa fa-trash fa-2x" aria-hidden="true"></i></a> </li>

                         @endforeach
                         </ul>

                     @endif





                </div>
            </div>
        </div>
    </div>
</div>

@endsection

@section('script')
<script>
var typeid = {{ $typeid }};


</script>
<script src="{{ url(elixir('js/imageuploader.js')) }}"></script>
@endsection

resources/views/admin/type/index.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
    <div class="row">
        <div class="col-md-10 col-md-offset-1">
            <div class="panel panel-default">
                <div class="panel-heading"><h3>Product Types</h3>
                <form method="POST" action="filter/{{ $filterKey }}" class="form-inline">
                    <div class="form-group">
                        <input type="hidden" name="_token" value="{{ csrf_token() }}" />

                        <label>Search key</label>
                        <input class="form-control" type="text" name="fkey[or]" value="{{ json_decode( session( env('USER_FILTER_KEY').$filterKey),true)['fkey']['or'] }}" />



                        <button type="submit" name="Filter" class="btn btn-default"><i class="fa fa-filter fa-1x"></i> Filter list</button>

                        @if( session( env('USER_FILTER_KEY').$filterKey) )
                        <button type="submit" name="remove_filter" value="1" class="btn btn-default"><i class="fa fa-eraser fa-1x"></i> Remove filter</button>
                        @endif

                    </div>
                </form>
                </div>

                <div class="panel-body">

                    <div class="row">

                        <div class="col-md-12"><a href="{{ route('type.create') }}"><button class="btn btn-primary pull-right"><i class="fa fa-plus-square-o fa-1x"></i> Create a new product type</button></a></div>
                    </div>




                    <table class="table table-striped">
                    <thead>
                        <tr>
                            <th>TypeID</th>
                            <th>Product type</th>
                            <th>Description</th>
                            <th>Display direction</th>
                            <th>&nbsp;</th>
                        </tr>
                    </thead>
                    <tbody>
                    @foreach($types as $type)
                    <tr>
                    	<td>{{ $type->typeid }}</td>
                        <td>{{ $type->name }}</td>
                        <td>{{ $type->type_description }}</td>
                         <td>{{ $type->display_format }}</td>
                    	<td width="20"><a href="{{ route('type.edit', ['id' => $type->typeid] ) }}"><i class="fa fa-pencil-square-o fa-1x" aria-hidden="true"></i></a></td>
                    </tr>
                    @endforeach

                    </tbody>
                    </table>
                    {{ $types->links() }}
                </div>
            </div>
        </div>
    </div>
</div>
@endsection

resources/views/admin/type/type_categories.blade.php
@extends('layouts.app');


@section('content')
<div class="container">

	<h1>Type Categories Edit Form</h1>

	<p style="color:red">Use CTRL Click to select multiple categories</p>

	<h3>{{ $type->name }}</h3>



	<div class="row">
		<div class="col-md-6 col-xs-12">
			{!! Form::open(['route' => ['typecategory.update',$type->typeid], 'method' => 'PATCH']) !!}

			<div class="form-group">
				<label for="categories[]" >Display Categories</label>
				<select class="form-control" id="categories" name="categories[]" multiple="multiple" size="20">
				<option value=0 >----None----</option>
				@foreach($categories as $category)

				<option {{ $type->categories->contains($category->id) ? ' selected ' : '' }} value="{{ $category->id }}">{{ $category->name }}</option>
					@foreach($category->children as $child)
						<option {{ $type->categories->contains($child->id) ? ' selected ' : '' }} value="{{ $child->id }}">-- {{ $child->name }}</option>
					@endforeach

				@endforeach

				</select>
			</div>



			<button type="submit" name="b" class="btn btn-primary">Update</button>

			{!! Form::close() !!}
		</div>
	</div>

</div>


@endsection